version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: la-react-postgres
    environment:
      POSTGRES_DB: la_react_db_local
      POSTGRES_USER: tinntinn
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 