version: "3.9"
services:
    app:
        build: .
        ports:
            - "8000:80"
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=la-react
            - DB_USERNAME=postgres
            - DB_PASSWORD=secret
        depends_on:
            - postgres
    postgres:
        image: postgres:15
        environment:
            POSTGRES_DB: la-react
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
